# Generated by Django 3.2.25 on 2025-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_no', models.CharField(blank=True, max_length=155, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=155, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('ali_trade_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.PositiveIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_num', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True, verbose_name='事件ID')),
                ('event_type', models.CharField(max_length=32, verbose_name='事件类型')),
                ('event_data', models.JSONField(verbose_name='事件数据')),
                ('status', models.CharField(choices=[('pending', '待消费'), ('success', '已消费'), ('fail', '消费失败')], max_length=10, verbose_name='事件状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '事件日志',
                'verbose_name_plural': '事件日志',
                'db_table': 'event_log',
            },
        ),
        migrations.CreateModel(
            name='LocalTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='事务ID（用订单号trade_no）')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('fail', '失败')], default='pending', max_length=10, verbose_name='事务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '本地事务记录',
                'verbose_name_plural': '本地事务记录',
                'db_table': 'local_transaction_record',
            },
        ),
    ]
