# Generated by Django 5.2.6 on 2025-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.CharField(max_length=255)),
                ("nums", models.IntegerField()),
                ("is_delete", models.IntegerField()),
                ("email", models.CharField(max_length=255)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shopping_cart",
                "managed": False,
            },
        ),
    ]
