# Generated by Django 5.2.6 on 2025-10-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'managed': True},
        ),
    ]
