# Generated by Django 5.2.6 on 2025-10-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_seckill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='seckill_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='seckill_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='seckill_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='seckill_stock',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
