# Generated by Django 5.2.6 on 2025-09-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeiboProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(max_length=255, verbose_name="微博access_token"),
                ),
                (
                    "wuid",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="微博用户唯一ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weibo_profile",
                        to="user.user",
                        verbose_name="关联系统用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "微博用户关联表",
                "verbose_name_plural": "微博用户关联表",
                "db_table": "weibo_profile",
            },
        ),
    ]
