# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_weiboprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weiboprofile",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                db_column="user_profile_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weibo_profile",
                to="user.user",
                verbose_name="关联系统用户",
            ),
        ),
    ]
