# Generated by Django 5.2.6 on 2025-10-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_weiboprofile_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weiboprofile',
            options={'managed': False, 'verbose_name': '微博用户关联表', 'verbose_name_plural': '微博用户关联表'},
        ),
    ]
