"""
Django settings for muxi_shop_api2 project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
# 把apps 加入到项目根的搜素路径，导入的时候，可以直接从源码包中导入
sys.path.insert(0, BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "user",
    "cart",
    "goods",
    "order",
    "comment",
    "menu",
    "address",
    "pay",
    "seckill",
    "stock",
    "rest_framework",
    "corsheaders",
    "django_elasticsearch_dsl",
    "channels",
    "analytics",
    
]
# ===== ES 连接配置 =====
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'localhost:9200',
    },
}

# 解决跨域的一个插件
# pip install django-cors-headers
# 允许所有域名跨域
CORS_ORIGIN_ALLOW_ALL=True
# 允许携带cookie
CORS_ALLOW_CREDENTIALS=True
# 允许请求方式
CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "DELETE", "OPTIONS",  # 允许OPTIONS方法
]

MIDDLEWARE = [
    # 1. 全局异常捕获
    'middleware.error_middleware.GlobalErrorMiddleware',
    # 2. prometheus 监控中间件
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    # 3. 安全相关中间件（最靠前，优先处理安全问题）
    "django.middleware.security.SecurityMiddleware",
    # 4. Session 中间件（处理用户会话，需在 CORS 之前）
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 5. CORS 中间件（官方推荐位置：Session 之后，Common 之前）
    "corsheaders.middleware.CorsMiddleware",
    # 6. 通用中间件（处理请求路径、缓存等）
    "django.middleware.common.CommonMiddleware",
    # 7. CSRF 中间件（开发环境可临时注释，生产环境必须打开！）
    "django.middleware.csrf.CsrfViewMiddleware",
    # 8. 认证中间件（处理用户登录状态）
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 9. 消息中间件（处理 Django 消息提示）
    "django.contrib.messages.middleware.MessageMiddleware",
    # 10. 点击劫持防护中间件
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "muxi_shop_api2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ROOT_URLCONF = "muxi_shop_api2.urls"

WSGI_APPLICATION = "muxi_shop_api2.wsgi.application"

ASGI_APPLICATION = 'muxi_shop_api2.asgi.application' 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# 这个是图片的访问路径
# 我们的图片访问路径是: https://lcalhost:8080/static/product_images/268357.jpg

# 需要配置文件所在路径（文件夹）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",  # 所有环境都用 Redis 缓存
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection._HiredisParser",  # 可选：加速解析
        }
    },
    "sms": {
        "BACKEND": "django_redis.cache.RedisCache",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "carts": {
        "BACKEND": "django_redis.cache.RedisCache",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "seckill": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 配置Redis通道层（最终正确版本）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # 正确格式：URL 中指定 3 号库，无单独 db 参数
            "hosts": ["redis://127.0.0.1:6379/3"],
            "capacity": 1500,
            "expiry": 300,
            "group_expiry": 60,
        },
    },
}
# 全局的token验证配置
REST_FRAMEWORK = {
    # 分页配置（如果需要分页功能）
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 10,  # 每页显示10条数据

    # 认证类配置（这里才是放置认证类的正确位置）
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "utils.jwt_auth.JWTHeaderAuthentication",  # JWT认证类
    ],
}







