"""
Django settings for muxi_shop_api2 project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 把apps 加入到项目根的搜素路径，导入的时候，可以直接从源码包中导入
sys.path.insert(0, BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l!fnpi@_wq53xk62d@cjpo5t_e)n!uqj$_u9r&tv6x8$fzsd01"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.user",
    "apps.cart",
    "apps.goods",
    "apps.order",
    "apps.comment",
    "apps.menu",
    "apps.address",
    "apps.pay",
    "apps.seckill",
    "rest_framework",
    "corsheaders",



]

# 解决跨域的一个插件
# pip install django-cors-headers
# 允许所有域名跨域
CORS_ORIGIN_ALLOW_ALL=True
# 允许携带cookie
CORS_ALLOW_CREDENTIALS=True
# 允许请求方式
CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "DELETE", "OPTIONS",  # 允许OPTIONS方法
]

MIDDLEWARE = [
    # 1. 安全相关中间件（最靠前，优先处理安全问题）
    "django.middleware.security.SecurityMiddleware",
    # 2. Session 中间件（处理用户会话，需在 CORS 之前）
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 3. CORS 中间件（官方推荐位置：Session 之后，Common 之前）
    "corsheaders.middleware.CorsMiddleware",
    # 4. 通用中间件（处理请求路径、缓存等）
    "django.middleware.common.CommonMiddleware",
    # 5. CSRF 中间件（开发环境可临时注释，生产环境必须打开！）
    "django.middleware.csrf.CsrfViewMiddleware",
    # 6. 认证中间件（处理用户登录状态）
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 7. 消息中间件（处理 Django 消息提示）
    "django.contrib.messages.middleware.MessageMiddleware",
    # 8. 点击劫持防护中间件
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "muxi_shop_api2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "muxi_shop_api2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# settings.py 中正确的 MySQL 配置格式
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",  # 固定字符串，指定引擎
        "NAME": "muxi_shop",                   # 数据库名（必须是字符串，不要加 BASE_DIR）
        "USER": "admin1",                      # 数据库用户名（字符串）
        "PASSWORD": "123",                     # 数据库密码（字符串！不要用 Path 或路径拼接）
        "HOST": "192.168.80.144",              # 数据库服务IP（字符串）
        "PORT": "3306",                        # 数据库端口（字符串，MySQL默认3306，必须加引号）
        # 可选：添加额外配置避免编码问题
        "OPTIONS": {
            "charset": "utf8mb4",
            "use_unicode": True,
            # "connect_timeout": 10,
            # "autocommit": True,
        },
        # Django 连接池配置
        "CONN_MAX_AGE": 60, # 连接最大存活时间0秒
        "TEST": {
            "NAME": "test_muxi_shop",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# 这个是图片的访问路径
# 我们的图片访问路径是: https://lcalhost:8080/static/product_images/268357.jpg
STATIC_URL = "static/"
# 需要配置文件所在路径（文件夹）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# 静态文件服务器配置
IMAGE_URL="http://localhost:8000/static/product_images/"
USER_AVATAR_URL = "http://localhost:8000/static/user_avatars/"
USER_BACKGROUND_URL = "http://localhost:8000/static/user_backgrounds/"
# 全局的token验证配置
REST_FRAMEWORK = {
    # 分页配置（如果需要分页功能）
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 10,  # 每页显示10条数据

    # 认证类配置（这里才是放置认证类的正确位置）
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "utils.jwt_auth.JWTHeaderAuthentication",  # 你的JWT认证类
    ],
}

# muxi_shop_api2/settings.py（只保留Celery和Redis相关配置，其他不变）

#####################Redis缓存的配置开始#####################
CACHES = {
    'default':{
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.80.144:6379/0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    },
    'sms': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.80.144:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    },
    'carts': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.80.144:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    },
    'seckill': {  # 秒杀专用Redis库（3号库）
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.80.144:6379/3',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'decode_responses': True
            }
        }
    }
}
REDIS_TIMEOUT = 300  # 验证码有效期5分钟
#####################Redis缓存的配置结束#####################

#####################Celery 配置开始（修正后）####################
# 1. 修正自引用错误：直接取 CACHES['seckill']['LOCATION']，不用加 settings.
CELERY_BROKER_URL = CACHES['seckill']['LOCATION']  # 消息队列（3号库）
CELERY_RESULT_BACKEND = CELERY_BROKER_URL  # 结果存储（和消息队列同库）
CELERY_TIMEZONE = 'Asia/Shanghai'  # 时区
CELERY_ACCEPT_CONTENT = ['json']  # 接受的消息格式
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化

# 2. 新增：解决数据库线程安全问题的关键配置
CELERYD_MAX_TASKS_PER_CHILD = 10  # 每个Worker处理10个任务后重启（释放旧连接）
CELERYD_CONCURRENCY = 4  # 并发数（根据CPU调整，避免线程过多）
CELERY_TASK_ACKS_LATE = True  # 任务执行完再确认（避免连接未释放）
#####################Celery 配置结束####################


#####################邮件服务器配置开始#####################

# 邮件服务器的后端
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 邮件服务器的地址
EMAIL_HOST = 'smtp.qq.com'

# 邮件服务器的用户名

EMAIL_HOST_USER = '2350496649@qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # 注意：QQ 邮箱 587 端口用 TLS，465 用 SSL


# 邮件服务器使用的密码
EMAIL_HOST_PASSWORD = 'hkznmqkazshqeagg'
DEFAULT_FROM_EMAIL = "木犀商城 <2350496649@qq.com>"

#####################邮件服务器配置结束######################

#####################新浪微博的配置开始#####################

WEIBO_APP_KEY = '780919870'

WEIBO_APP_SECRET = '298c445669e83b882df28909d3520e1a'

WEIBO_REDIRECT_URI = 'http://127.0.0.1/weibo/callback' # 回调页URL

#####################新浪微博的配置结束#####################

#####################支付宝沙箱环境配置开始##################
APPID = '9021000155668647'
ALI_PUB_KEY_PATH=os.path.join(BASE_DIR, 'apps/pay/keys/alipay_key.txt')
PRIVATE_KEY_PATH=os.path.join(BASE_DIR, "apps/pay/keys/private_key.txt")
# 异步接收url post请求
APP_NOTIFY_URL="http://127.0.0.1:8000/pay/alipay/return"

# 同步接收url 就是用户在页面上支付成功之后，然后就跳转的页面 get请求
RETURN_URL="http://127.0.0.1:8000/pay/alipay/return"

# 是否是开发环境
ALIPAY_DEBUG=True

#####################支付宝沙箱环境配置结束##################