# Generated by Django 5.2.6 on 2025-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "signer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telphone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "signer_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                ("default", models.IntegerField(blank=True, null=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_address",
                "managed": False,
            },
        ),
    ]
