# Generated by Django 3.2.25 on 2025-10-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_trade_no', models.CharField(max_length=64, verbose_name='关联订单编号')),
                ('goods_id', models.IntegerField(verbose_name='商品ID（关联Goods.id）')),
                ('qty', models.IntegerField(verbose_name='扣减/补偿数量')),
                ('tx_status', models.CharField(choices=[('deducted', '已扣减'), ('compensated', '已补偿'), ('failed', '失败')], default='deducted', max_length=16, verbose_name='事务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '库存事务记录',
                'db_table': 'stock_tx',
            },
        ),
    ]
